/**
* ViewSession.js
*
* @description :: This model represents the video sessions to store view data
* @docs        :: http://sailsjs.org/#!documentation/models
*/

module.exports = {
	attributes: {
		// this should be a uuid generated by frontend to identify the correct session
		sessionId: {
			type: 'string',
			required: true
		},

		// Add a reference to Video
		videoId: {
			model: 'Video'
		},

		// Add a reference to ViewData
		viewLogs: {
			collection: 'ViewData',
			via: 'sessionObj'
		}
	}
}
